# Generated by Django 4.2.3 on 2023-07-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacebookPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=255)),
                ("post_content", models.TextField()),
                ("likes", models.IntegerField(default=0)),
                ("comments", models.IntegerField(default=0)),
                ("shares", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=255)),
                ("post_content", models.TextField()),
                ("keyword", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Tweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=255)),
                ("created_at", models.CharField(max_length=255)),
                ("full_text", models.TextField()),
                ("user_name", models.CharField(max_length=255)),
                ("screen_name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("followers_count", models.IntegerField()),
                ("friends_count", models.IntegerField()),
                ("lang", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default=None, max_length=100)),
                ("location", models.CharField(default=None, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New Lead"),
                            ("engaged", "Engaged Lead"),
                            ("qualified", "Qualified Lead"),
                            ("converted", "Converted Lead"),
                            ("lost", "Lost Lead"),
                        ],
                        default="new",
                        max_length=100,
                    ),
                ),
                (
                    "handled_by",
                    models.ManyToManyField(
                        default=None, null=True, to="authentication.employee"
                    ),
                ),
            ],
        ),
    ]
